version: '3.1'

services:
  db:
    container_name: hs-workshop-rest-api
    image: "postgres:10-alpine"
    restart: always
    ports:
      - "5432:5432"
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: "pwd"
      POSTGRES_USER: "user"